
export const DEFAULT_RECONNECT_ENABLED = true;
export const DEFAULT_RECONNECT_MAX_ATTEMPTS = 20;
export const DEFAULT_RECONNECT_BASE_DELAY_MS = 500;
export const DEFAULT_RECONNECT_MAX_DELAY_MS = 30000;
export const DEFAULT_REQUEST_TIMEOUT_MS = 15000;
